//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 5/3/2010 8:09:18 AM
namespace WaveTech.CMWatcher.Repositories.SqLiteRepository
{
    
    /// <summary>
    /// There are no comments for CMWatcherEntities in the schema.
    /// </summary>
    public partial class CMWatcherEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CMWatcherEntities object using the connection string found in the 'CMWatcherEntities' section of the application configuration file.
        /// </summary>
        public CMWatcherEntities() : 
                base("name=CMWatcherEntities", "CMWatcherEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CMWatcherEntities object.
        /// </summary>
        public CMWatcherEntities(string connectionString) : 
                base(connectionString, "CMWatcherEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CMWatcherEntities object.
        /// </summary>
        public CMWatcherEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CMWatcherEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ConfigurationOptions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ConfigurationOptions> ConfigurationOptions
        {
            get
            {
                if ((this._ConfigurationOptions == null))
                {
                    this._ConfigurationOptions = base.CreateQuery<ConfigurationOptions>("[ConfigurationOptions]");
                }
                return this._ConfigurationOptions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ConfigurationOptions> _ConfigurationOptions;
        /// <summary>
        /// There are no comments for ConnectionFailures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ConnectionFailures> ConnectionFailures
        {
            get
            {
                if ((this._ConnectionFailures == null))
                {
                    this._ConnectionFailures = base.CreateQuery<ConnectionFailures>("[ConnectionFailures]");
                }
                return this._ConnectionFailures;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ConnectionFailures> _ConnectionFailures;
        /// <summary>
        /// There are no comments for ConfigurationOptions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToConfigurationOptions(ConfigurationOptions configurationOptions)
        {
            base.AddObject("ConfigurationOptions", configurationOptions);
        }
        /// <summary>
        /// There are no comments for ConnectionFailures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToConnectionFailures(ConnectionFailures connectionFailures)
        {
            base.AddObject("ConnectionFailures", connectionFailures);
        }
    }
    /// <summary>
    /// There are no comments for CMWatcherModel.ConfigurationOptions in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ConfigurationOptionId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CMWatcherModel", Name="ConfigurationOptions")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ConfigurationOptions : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ConfigurationOptions object.
        /// </summary>
        /// <param name="configurationOptionId">Initial value of ConfigurationOptionId.</param>
        /// <param name="modemIPAddress">Initial value of ModemIPAddress.</param>
        /// <param name="modemSignalPageUrl">Initial value of ModemSignalPageUrl.</param>
        /// <param name="modemLogPageUrl">Initial value of ModemLogPageUrl.</param>
        /// <param name="monitorAddress">Initial value of MonitorAddress.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ConfigurationOptions CreateConfigurationOptions(long configurationOptionId, string modemIPAddress, string modemSignalPageUrl, string modemLogPageUrl, string monitorAddress)
        {
            ConfigurationOptions configurationOptions = new ConfigurationOptions();
            configurationOptions.ConfigurationOptionId = configurationOptionId;
            configurationOptions.ModemIPAddress = modemIPAddress;
            configurationOptions.ModemSignalPageUrl = modemSignalPageUrl;
            configurationOptions.ModemLogPageUrl = modemLogPageUrl;
            configurationOptions.MonitorAddress = monitorAddress;
            return configurationOptions;
        }
        /// <summary>
        /// There are no comments for property ConfigurationOptionId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long ConfigurationOptionId
        {
            get
            {
                return this._ConfigurationOptionId;
            }
            set
            {
                this.OnConfigurationOptionIdChanging(value);
                this.ReportPropertyChanging("ConfigurationOptionId");
                this._ConfigurationOptionId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ConfigurationOptionId");
                this.OnConfigurationOptionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _ConfigurationOptionId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConfigurationOptionIdChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConfigurationOptionIdChanged();
        /// <summary>
        /// There are no comments for property ModemIPAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ModemIPAddress
        {
            get
            {
                return this._ModemIPAddress;
            }
            set
            {
                this.OnModemIPAddressChanging(value);
                this.ReportPropertyChanging("ModemIPAddress");
                this._ModemIPAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModemIPAddress");
                this.OnModemIPAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ModemIPAddress;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemIPAddressChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemIPAddressChanged();
        /// <summary>
        /// There are no comments for property ModemSignalPageUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ModemSignalPageUrl
        {
            get
            {
                return this._ModemSignalPageUrl;
            }
            set
            {
                this.OnModemSignalPageUrlChanging(value);
                this.ReportPropertyChanging("ModemSignalPageUrl");
                this._ModemSignalPageUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModemSignalPageUrl");
                this.OnModemSignalPageUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ModemSignalPageUrl;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemSignalPageUrlChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemSignalPageUrlChanged();
        /// <summary>
        /// There are no comments for property ModemLogPageUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ModemLogPageUrl
        {
            get
            {
                return this._ModemLogPageUrl;
            }
            set
            {
                this.OnModemLogPageUrlChanging(value);
                this.ReportPropertyChanging("ModemLogPageUrl");
                this._ModemLogPageUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModemLogPageUrl");
                this.OnModemLogPageUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ModemLogPageUrl;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemLogPageUrlChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemLogPageUrlChanged();
        /// <summary>
        /// There are no comments for property ModemUsername in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ModemUsername
        {
            get
            {
                return this._ModemUsername;
            }
            set
            {
                this.OnModemUsernameChanging(value);
                this.ReportPropertyChanging("ModemUsername");
                this._ModemUsername = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ModemUsername");
                this.OnModemUsernameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ModemUsername;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemUsernameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemUsernameChanged();
        /// <summary>
        /// There are no comments for property ModemPassword in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ModemPassword
        {
            get
            {
                return this._ModemPassword;
            }
            set
            {
                this.OnModemPasswordChanging(value);
                this.ReportPropertyChanging("ModemPassword");
                this._ModemPassword = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ModemPassword");
                this.OnModemPasswordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ModemPassword;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemPasswordChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModemPasswordChanged();
        /// <summary>
        /// There are no comments for property MonitorAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string MonitorAddress
        {
            get
            {
                return this._MonitorAddress;
            }
            set
            {
                this.OnMonitorAddressChanging(value);
                this.ReportPropertyChanging("MonitorAddress");
                this._MonitorAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("MonitorAddress");
                this.OnMonitorAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _MonitorAddress;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMonitorAddressChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMonitorAddressChanged();
        /// <summary>
        /// There are no comments for property Profile in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Profile
        {
            get
            {
                return this._Profile;
            }
            set
            {
                this.OnProfileChanging(value);
                this.ReportPropertyChanging("Profile");
                this._Profile = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Profile");
                this.OnProfileChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Profile;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProfileChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProfileChanged();
    }
    /// <summary>
    /// There are no comments for CMWatcherModel.ConnectionFailures in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ConnectionFailureId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CMWatcherModel", Name="ConnectionFailures")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ConnectionFailures : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ConnectionFailures object.
        /// </summary>
        /// <param name="connectionFailureId">Initial value of ConnectionFailureId.</param>
        /// <param name="startTimestamp">Initial value of StartTimestamp.</param>
        /// <param name="endTimestamp">Initial value of EndTimestamp.</param>
        /// <param name="screenShotsPath">Initial value of ScreenShotsPath.</param>
        /// <param name="data">Initial value of Data.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ConnectionFailures CreateConnectionFailures(long connectionFailureId, global::System.DateTime startTimestamp, global::System.DateTime endTimestamp, string screenShotsPath, string data)
        {
            ConnectionFailures connectionFailures = new ConnectionFailures();
            connectionFailures.ConnectionFailureId = connectionFailureId;
            connectionFailures.StartTimestamp = startTimestamp;
            connectionFailures.EndTimestamp = endTimestamp;
            connectionFailures.ScreenShotsPath = screenShotsPath;
            connectionFailures.Data = data;
            return connectionFailures;
        }
        /// <summary>
        /// There are no comments for property ConnectionFailureId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long ConnectionFailureId
        {
            get
            {
                return this._ConnectionFailureId;
            }
            set
            {
                this.OnConnectionFailureIdChanging(value);
                this.ReportPropertyChanging("ConnectionFailureId");
                this._ConnectionFailureId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ConnectionFailureId");
                this.OnConnectionFailureIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _ConnectionFailureId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConnectionFailureIdChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConnectionFailureIdChanged();
        /// <summary>
        /// There are no comments for property StartTimestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime StartTimestamp
        {
            get
            {
                return this._StartTimestamp;
            }
            set
            {
                this.OnStartTimestampChanging(value);
                this.ReportPropertyChanging("StartTimestamp");
                this._StartTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StartTimestamp");
                this.OnStartTimestampChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _StartTimestamp;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStartTimestampChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStartTimestampChanged();
        /// <summary>
        /// There are no comments for property EndTimestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime EndTimestamp
        {
            get
            {
                return this._EndTimestamp;
            }
            set
            {
                this.OnEndTimestampChanging(value);
                this.ReportPropertyChanging("EndTimestamp");
                this._EndTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndTimestamp");
                this.OnEndTimestampChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _EndTimestamp;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEndTimestampChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEndTimestampChanged();
        /// <summary>
        /// There are no comments for property ScreenShotsPath in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ScreenShotsPath
        {
            get
            {
                return this._ScreenShotsPath;
            }
            set
            {
                this.OnScreenShotsPathChanging(value);
                this.ReportPropertyChanging("ScreenShotsPath");
                this._ScreenShotsPath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ScreenShotsPath");
                this.OnScreenShotsPathChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ScreenShotsPath;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnScreenShotsPathChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnScreenShotsPathChanged();
        /// <summary>
        /// There are no comments for property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Data;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDataChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDataChanged();
    }
}
