//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveTech.CMWatcher.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveTech.CMWatcher.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Init Called..
        /// </summary>
        internal static string Msg_Monitor_InitCalled {
            get {
                return ResourceManager.GetString("Msg_Monitor_InitCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===================INTERNET CONNECTION FAILURE===================.
        /// </summary>
        internal static string Msg_Monitor_WorkerConnectionErrorHeader {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerConnectionErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Process Finsihed..
        /// </summary>
        internal static string Msg_Monitor_WorkerFinished {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not ping the modem&apos;s IPAddress..
        /// </summary>
        internal static string Msg_Monitor_WorkerModemPingFailed {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerModemPingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External IP to monitor responded..
        /// </summary>
        internal static string Msg_Monitor_WorkerPingSuccess {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerPingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External IP to monitor timed out..
        /// </summary>
        internal static string Msg_Monitor_WorkerPingTimeout {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerPingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous connection failure was deteced, started on {0} and has recovered on {1}..
        /// </summary>
        internal static string Msg_Monitor_WorkerPreviousFailureDetected {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerPreviousFailureDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous failure was detected, so skipping logging current failure..
        /// </summary>
        internal static string Msg_Monitor_WorkerPreviousFailureDetectedSkip {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerPreviousFailureDetectedSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Process Started..
        /// </summary>
        internal static string Msg_Monitor_WorkerStarted {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing the Singal and Log pages of the Modem..
        /// </summary>
        internal static string Msg_Monitor_WorkerStartingModemPagesCapture {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerStartingModemPagesCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monitor worker thread is sleeping for {0} msecs..
        /// </summary>
        internal static string Msg_Monitor_WorkerThreadSleep {
            get {
                return ResourceManager.GetString("Msg_Monitor_WorkerThreadSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Init Finished..
        /// </summary>
        internal static string Msg_Montior_InitFinished {
            get {
                return ResourceManager.GetString("Msg_Montior_InitFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the screen shots to the directory: {0}.
        /// </summary>
        internal static string Msg_Montior_WorkerSavingPath {
            get {
                return ResourceManager.GetString("Msg_Montior_WorkerSavingPath", resourceCulture);
            }
        }
    }
}
